version: '3.8'

services:
  rust-playground:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - RUST_LOG=info
    container_name: rust-playground
